name: Deploy Ghost Theme

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy theme to Ghost
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Deploy theme
        uses: TryGhost/action-deploy-theme@v1.7.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
